import React, { useState, useEffect } from "react";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import Drawer from "@mui/material/Drawer";
import axios from "axios";

import {
  CssBaseline,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Grid,
  Container,
} from "@mui/material";

const likedSongs = {
  href: "https://api.spotify.com/v1/me/tracks?offset=0&limit=8",
  items: [
    {
      added_at: "2023-05-29T21:00:42Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs",
              },
              href: "https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs",
              id: "6USv9qhCn6zfxlBQIYJ9qs",
              name: "Dominic Fike",
              type: "artist",
              uri: "spotify:artist:6USv9qhCn6zfxlBQIYJ9qs",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1BubKJqf6Uc4fNae5kLJJ7",
          },
          href: "https://api.spotify.com/v1/albums/1BubKJqf6Uc4fNae5kLJJ7",
          id: "1BubKJqf6Uc4fNae5kLJJ7",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273cfc824b65a3b1755d98a7e23",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02cfc824b65a3b1755d98a7e23",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851cfc824b65a3b1755d98a7e23",
              width: 64,
            },
          ],
          name: "What Could Possibly Go Wrong",
          release_date: "2020-07-31",
          release_date_precision: "day",
          total_tracks: 14,
          type: "album",
          uri: "spotify:album:1BubKJqf6Uc4fNae5kLJJ7",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6USv9qhCn6zfxlBQIYJ9qs",
            },
            href: "https://api.spotify.com/v1/artists/6USv9qhCn6zfxlBQIYJ9qs",
            id: "6USv9qhCn6zfxlBQIYJ9qs",
            name: "Dominic Fike",
            type: "artist",
            uri: "spotify:artist:6USv9qhCn6zfxlBQIYJ9qs",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 127054,
        explicit: false,
        external_ids: {
          isrc: "USQX92003251",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/20j7l6tFtc5lynXpbOQg1O",
        },
        href: "https://api.spotify.com/v1/tracks/20j7l6tFtc5lynXpbOQg1O",
        id: "20j7l6tFtc5lynXpbOQg1O",
        is_local: false,
        name: "Superstar Sh*t",
        popularity: 73,
        preview_url:
          "https://p.scdn.co/mp3-preview/04f0bbe5b7d5fe484bc93820f015f5ee30923dae?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 10,
        type: "track",
        uri: "spotify:track:20j7l6tFtc5lynXpbOQg1O",
      },
    },
    {
      added_at: "2023-05-29T20:36:59Z",
      track: {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/2CIdibKYdqFN9ivfLFA7hj",
              },
              href: "https://api.spotify.com/v1/artists/2CIdibKYdqFN9ivfLFA7hj",
              id: "2CIdibKYdqFN9ivfLFA7hj",
              name: "Cab'Ral",
              type: "artist",
              uri: "spotify:artist:2CIdibKYdqFN9ivfLFA7hj",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6xorgakhf8qnntQ87jUqa2",
          },
          href: "https://api.spotify.com/v1/albums/6xorgakhf8qnntQ87jUqa2",
          id: "6xorgakhf8qnntQ87jUqa2",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273f3d619fb868556d8d45e133d",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02f3d619fb868556d8d45e133d",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851f3d619fb868556d8d45e133d",
              width: 64,
            },
          ],
          name: "Take Time",
          release_date: "2019-02-08",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:6xorgakhf8qnntQ87jUqa2",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2CIdibKYdqFN9ivfLFA7hj",
            },
            href: "https://api.spotify.com/v1/artists/2CIdibKYdqFN9ivfLFA7hj",
            id: "2CIdibKYdqFN9ivfLFA7hj",
            name: "Cab'Ral",
            type: "artist",
            uri: "spotify:artist:2CIdibKYdqFN9ivfLFA7hj",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 124534,
        explicit: false,
        external_ids: {
          isrc: "QZ8LD1971067",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/7GP3IRyzvsEMMKgG8bZLXC",
        },
        href: "https://api.spotify.com/v1/tracks/7GP3IRyzvsEMMKgG8bZLXC",
        id: "7GP3IRyzvsEMMKgG8bZLXC",
        is_local: false,
        name: "Take Time",
        popularity: 62,
        preview_url:
          "https://p.scdn.co/mp3-preview/acb547b91ed01bb86c3688c4e5e7de1c7e76a423?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 1,
        type: "track",
        uri: "spotify:track:7GP3IRyzvsEMMKgG8bZLXC",
      },
    },
    {
      added_at: "2023-05-27T22:43:21Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
              },
              href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
              id: "4LLpKhyESsyAXpc4laK94U",
              name: "Mac Miller",
              type: "artist",
              uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/17mAoDs7T8EA9zzlj6QPBv",
          },
          href: "https://api.spotify.com/v1/albums/17mAoDs7T8EA9zzlj6QPBv",
          id: "17mAoDs7T8EA9zzlj6QPBv",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273fef67ba7527cc0aa2ec6edf8",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02fef67ba7527cc0aa2ec6edf8",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851fef67ba7527cc0aa2ec6edf8",
              width: 64,
            },
          ],
          name: "Blue Slide Park",
          release_date: "2011-11-08",
          release_date_precision: "day",
          total_tracks: 16,
          type: "album",
          uri: "spotify:album:17mAoDs7T8EA9zzlj6QPBv",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
            },
            href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
            id: "4LLpKhyESsyAXpc4laK94U",
            name: "Mac Miller",
            type: "artist",
            uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 178902,
        explicit: true,
        external_ids: {
          isrc: "USQY51145588",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/2ySc7XpO3sdt01UG986MwE",
        },
        href: "https://api.spotify.com/v1/tracks/2ySc7XpO3sdt01UG986MwE",
        id: "2ySc7XpO3sdt01UG986MwE",
        is_local: false,
        name: "Missed Calls",
        popularity: 67,
        preview_url:
          "https://p.scdn.co/mp3-preview/b38d23bf0cc3855bb708e5bd3d9291cb91d76e0f?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 14,
        type: "track",
        uri: "spotify:track:2ySc7XpO3sdt01UG986MwE",
      },
    },
    {
      added_at: "2023-05-27T22:34:54Z",
      track: {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4zoRNhOhsGX3w8yBAnFSQ8",
              },
              href: "https://api.spotify.com/v1/artists/4zoRNhOhsGX3w8yBAnFSQ8",
              id: "4zoRNhOhsGX3w8yBAnFSQ8",
              name: "Paul Russell",
              type: "artist",
              uri: "spotify:artist:4zoRNhOhsGX3w8yBAnFSQ8",
            },
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4489Zgs4RNq2ZtSh3UnOxZ",
              },
              href: "https://api.spotify.com/v1/artists/4489Zgs4RNq2ZtSh3UnOxZ",
              id: "4489Zgs4RNq2ZtSh3UnOxZ",
              name: "Khary",
              type: "artist",
              uri: "spotify:artist:4489Zgs4RNq2ZtSh3UnOxZ",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/7qypqH6zU0ZowehywC9395",
          },
          href: "https://api.spotify.com/v1/albums/7qypqH6zU0ZowehywC9395",
          id: "7qypqH6zU0ZowehywC9395",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273b8c7ca1a63bfcd0a74539cef",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02b8c7ca1a63bfcd0a74539cef",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851b8c7ca1a63bfcd0a74539cef",
              width: 64,
            },
          ],
          name: "Ms. Poli Sci",
          release_date: "2022-11-11",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:7qypqH6zU0ZowehywC9395",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4zoRNhOhsGX3w8yBAnFSQ8",
            },
            href: "https://api.spotify.com/v1/artists/4zoRNhOhsGX3w8yBAnFSQ8",
            id: "4zoRNhOhsGX3w8yBAnFSQ8",
            name: "Paul Russell",
            type: "artist",
            uri: "spotify:artist:4zoRNhOhsGX3w8yBAnFSQ8",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4489Zgs4RNq2ZtSh3UnOxZ",
            },
            href: "https://api.spotify.com/v1/artists/4489Zgs4RNq2ZtSh3UnOxZ",
            id: "4489Zgs4RNq2ZtSh3UnOxZ",
            name: "Khary",
            type: "artist",
            uri: "spotify:artist:4489Zgs4RNq2ZtSh3UnOxZ",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 128703,
        explicit: true,
        external_ids: {
          isrc: "QM24S2205625",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/3imYkN34og7muZbkSZWLUW",
        },
        href: "https://api.spotify.com/v1/tracks/3imYkN34og7muZbkSZWLUW",
        id: "3imYkN34og7muZbkSZWLUW",
        is_local: false,
        name: "Ms. Poli Sci",
        popularity: 70,
        preview_url:
          "https://p.scdn.co/mp3-preview/0180afa4fe9eb3ebd2cd92546db628088a5db0dd?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 1,
        type: "track",
        uri: "spotify:track:3imYkN34og7muZbkSZWLUW",
      },
    },
    {
      added_at: "2023-05-27T15:05:52Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ",
              },
              href: "https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ",
              id: "7A0awCXkE1FtSU8B0qwOJQ",
              name: "Jamie xx",
              type: "artist",
              uri: "spotify:artist:7A0awCXkE1FtSU8B0qwOJQ",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4gaNWHu5Caj3ItkYZ5i6uh",
          },
          href: "https://api.spotify.com/v1/albums/4gaNWHu5Caj3ItkYZ5i6uh",
          id: "4gaNWHu5Caj3ItkYZ5i6uh",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2736aa1dfa0a98baa542251df5a",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e026aa1dfa0a98baa542251df5a",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048516aa1dfa0a98baa542251df5a",
              width: 64,
            },
          ],
          name: "In Colour",
          release_date: "2015-06-01",
          release_date_precision: "day",
          total_tracks: 11,
          type: "album",
          uri: "spotify:album:4gaNWHu5Caj3ItkYZ5i6uh",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7A0awCXkE1FtSU8B0qwOJQ",
            },
            href: "https://api.spotify.com/v1/artists/7A0awCXkE1FtSU8B0qwOJQ",
            id: "7A0awCXkE1FtSU8B0qwOJQ",
            name: "Jamie xx",
            type: "artist",
            uri: "spotify:artist:7A0awCXkE1FtSU8B0qwOJQ",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/50co4Is1HCEo8bhOyUWKpn",
            },
            href: "https://api.spotify.com/v1/artists/50co4Is1HCEo8bhOyUWKpn",
            id: "50co4Is1HCEo8bhOyUWKpn",
            name: "Young Thug",
            type: "artist",
            uri: "spotify:artist:50co4Is1HCEo8bhOyUWKpn",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/62DmErcU7dqZbJaDqwsqzR",
            },
            href: "https://api.spotify.com/v1/artists/62DmErcU7dqZbJaDqwsqzR",
            id: "62DmErcU7dqZbJaDqwsqzR",
            name: "Popcaan",
            type: "artist",
            uri: "spotify:artist:62DmErcU7dqZbJaDqwsqzR",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 213622,
        explicit: true,
        external_ids: {
          isrc: "UK7MC1500009",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/2fHFLyzAQYlguX5q0DfKlD",
        },
        href: "https://api.spotify.com/v1/tracks/2fHFLyzAQYlguX5q0DfKlD",
        id: "2fHFLyzAQYlguX5q0DfKlD",
        is_local: false,
        name: "I Know There's Gonna Be (Good Times)",
        popularity: 60,
        preview_url:
          "https://p.scdn.co/mp3-preview/85ddcc4c1385b8a26d6b1d6d65cf41fdf46037de?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 9,
        type: "track",
        uri: "spotify:track:2fHFLyzAQYlguX5q0DfKlD",
      },
    },
    {
      added_at: "2023-05-27T15:02:07Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4iMO20EPodreIaEl8qW66y",
              },
              href: "https://api.spotify.com/v1/artists/4iMO20EPodreIaEl8qW66y",
              id: "4iMO20EPodreIaEl8qW66y",
              name: "Still Woozy",
              type: "artist",
              uri: "spotify:artist:4iMO20EPodreIaEl8qW66y",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/0QnWm07An8WyO3eupjBDoP",
          },
          href: "https://api.spotify.com/v1/albums/0QnWm07An8WyO3eupjBDoP",
          id: "0QnWm07An8WyO3eupjBDoP",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273178df9e236187d6f1e710f5f",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02178df9e236187d6f1e710f5f",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851178df9e236187d6f1e710f5f",
              width: 64,
            },
          ],
          name: "If This Isn’t Nice, I Don’t Know What Is",
          release_date: "2021-08-13",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:0QnWm07An8WyO3eupjBDoP",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4iMO20EPodreIaEl8qW66y",
            },
            href: "https://api.spotify.com/v1/artists/4iMO20EPodreIaEl8qW66y",
            id: "4iMO20EPodreIaEl8qW66y",
            name: "Still Woozy",
            type: "artist",
            uri: "spotify:artist:4iMO20EPodreIaEl8qW66y",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 139293,
        explicit: false,
        external_ids: {
          isrc: "USUG12001158",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/42Fm8hxhh8i0Zx0Si7XIxd",
        },
        href: "https://api.spotify.com/v1/tracks/42Fm8hxhh8i0Zx0Si7XIxd",
        id: "42Fm8hxhh8i0Zx0Si7XIxd",
        is_local: false,
        name: "Window",
        popularity: 66,
        preview_url:
          "https://p.scdn.co/mp3-preview/d3add306990ec458648465c15743f8ee5ba45211?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 8,
        type: "track",
        uri: "spotify:track:42Fm8hxhh8i0Zx0Si7XIxd",
      },
    },
    {
      added_at: "2023-05-27T14:56:07Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
              },
              href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
              id: "4LLpKhyESsyAXpc4laK94U",
              name: "Mac Miller",
              type: "artist",
              uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5LNX3esjvdBJ6hN4XDvCJn",
          },
          href: "https://api.spotify.com/v1/albums/5LNX3esjvdBJ6hN4XDvCJn",
          id: "5LNX3esjvdBJ6hN4XDvCJn",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273c8a77225ad852699c908ac4b",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02c8a77225ad852699c908ac4b",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851c8a77225ad852699c908ac4b",
              width: 64,
            },
          ],
          name: "I Love Life, Thank You",
          release_date: "2022-07-22",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:5LNX3esjvdBJ6hN4XDvCJn",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
            },
            href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
            id: "4LLpKhyESsyAXpc4laK94U",
            name: "Mac Miller",
            type: "artist",
            uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4W48hZAnAHVOC2c8WH8pcq",
            },
            href: "https://api.spotify.com/v1/artists/4W48hZAnAHVOC2c8WH8pcq",
            id: "4W48hZAnAHVOC2c8WH8pcq",
            name: "The Temper Trap",
            type: "artist",
            uri: "spotify:artist:4W48hZAnAHVOC2c8WH8pcq",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 162875,
        explicit: true,
        external_ids: {
          isrc: "USA2P2212493",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/2z9iuAxKv4TTeCrPAxxKg9",
        },
        href: "https://api.spotify.com/v1/tracks/2z9iuAxKv4TTeCrPAxxKg9",
        id: "2z9iuAxKv4TTeCrPAxxKg9",
        is_local: false,
        name: "Love Lost",
        popularity: 80,
        preview_url:
          "https://p.scdn.co/mp3-preview/00be55b4568a2fe3985459db905d3e9ca2d845fd?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 5,
        type: "track",
        uri: "spotify:track:2z9iuAxKv4TTeCrPAxxKg9",
      },
    },
    {
      added_at: "2023-05-26T00:32:30Z",
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4hTL3jOgvZwOqegEZTOrCc",
              },
              href: "https://api.spotify.com/v1/artists/4hTL3jOgvZwOqegEZTOrCc",
              id: "4hTL3jOgvZwOqegEZTOrCc",
              name: "Col3trane",
              type: "artist",
              uri: "spotify:artist:4hTL3jOgvZwOqegEZTOrCc",
            },
          ],
          available_markets: [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5e0AwfXWMbFCC3qNDedM9j",
          },
          href: "https://api.spotify.com/v1/albums/5e0AwfXWMbFCC3qNDedM9j",
          id: "5e0AwfXWMbFCC3qNDedM9j",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27386672c714fd16a6e76ba2a02",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0286672c714fd16a6e76ba2a02",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485186672c714fd16a6e76ba2a02",
              width: 64,
            },
          ],
          name: "Lush Life",
          release_date: "2022-05-06",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:5e0AwfXWMbFCC3qNDedM9j",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4hTL3jOgvZwOqegEZTOrCc",
            },
            href: "https://api.spotify.com/v1/artists/4hTL3jOgvZwOqegEZTOrCc",
            id: "4hTL3jOgvZwOqegEZTOrCc",
            name: "Col3trane",
            type: "artist",
            uri: "spotify:artist:4hTL3jOgvZwOqegEZTOrCc",
          },
        ],
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        disc_number: 1,
        duration_ms: 143626,
        explicit: false,
        external_ids: {
          isrc: "QZMEV2211530",
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/4wLRzchJdARftJsHp4UqgO",
        },
        href: "https://api.spotify.com/v1/tracks/4wLRzchJdARftJsHp4UqgO",
        id: "4wLRzchJdARftJsHp4UqgO",
        is_local: false,
        name: "Lush Life",
        popularity: 54,
        preview_url:
          "https://p.scdn.co/mp3-preview/763968a7262ec135d30cab77a797eca488e5bf1b?cid=0b297fa8a249464ba34f5861d4140e58",
        track_number: 7,
        type: "track",
        uri: "spotify:track:4wLRzchJdARftJsHp4UqgO",
      },
    },
  ],
  limit: 8,
  next: "https://api.spotify.com/v1/me/tracks?offset=8&limit=8",
  offset: 0,
  previous: null,
  total: 336,
};
function MyLikedSongs() {
  const API_URL = "http://localhost:9000";
  const [selectedData, setSelectedData] = useState([]);

  const fetchData = async () => {
    try {
      const response = await axios.get(`${API_URL}/likedSongs`);
      setSelectedData(response.data.likedSongs);
    } catch (error) {
      console.error("Error retrieving top artists:", error);
    }
  };
  useEffect(() => {
    fetchData();
  }, []);
  return (
    <Container maxWidth="lg">
      <Grid container spacing={4} justify="left">
        {selectedData.map((song) => (
          <Grid item xs={12} sm={6} md={3} lg={3} key={song.track.id}>
            <Card style={{ height: "100%" }}>
              <CardMedia
                style={{ paddingTop: "56.35%" }}
                image={song.track.album.images[0].url}
                title={song.track.name}
              />
              <CardContent style={{ flexGrow: 1 }}>
                <Typography variant="h6" component="div" gutterBottom>
                  {song.track.name}
                </Typography>
                <Typography variant="subtitle1" color="textSecondary">
                  {song.track.artists[0].name}
                </Typography>
                <Typography variant="body2" color="textSecondary">
                  Popularity: {song.track.popularity}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Container>
  );
}

export default MyLikedSongs;
