import React, { useState } from "react";
import {
  Card,
  CardContent,
  CardMedia,
  Container,
  CssBaseline,
  Grid,
  MenuItem,
  Select,
  Typography,
} from "@mui/material";

const longTerm = {
  items: [
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0ONHkAv9pCAFxb0zJwDNTy",
            },
            href: "https://api.spotify.com/v1/artists/0ONHkAv9pCAFxb0zJwDNTy",
            id: "0ONHkAv9pCAFxb0zJwDNTy",
            name: "Pusha T",
            type: "artist",
            uri: "spotify:artist:0ONHkAv9pCAFxb0zJwDNTy",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6o38CdD7CUlZDCFhjZYLDH",
        },
        href: "https://api.spotify.com/v1/albums/6o38CdD7CUlZDCFhjZYLDH",
        id: "6o38CdD7CUlZDCFhjZYLDH",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273e27dfef438562f2ecb98a642",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02e27dfef438562f2ecb98a642",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851e27dfef438562f2ecb98a642",
            width: 64,
          },
        ],
        name: "It's Almost Dry",
        release_date: "2022-04-22",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:6o38CdD7CUlZDCFhjZYLDH",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0ONHkAv9pCAFxb0zJwDNTy",
          },
          href: "https://api.spotify.com/v1/artists/0ONHkAv9pCAFxb0zJwDNTy",
          id: "0ONHkAv9pCAFxb0zJwDNTy",
          name: "Pusha T",
          type: "artist",
          uri: "spotify:artist:0ONHkAv9pCAFxb0zJwDNTy",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x",
          },
          href: "https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x",
          id: "5K4W6rqBFWDnAN6FQUkS6x",
          name: "Kanye West",
          type: "artist",
          uri: "spotify:artist:5K4W6rqBFWDnAN6FQUkS6x",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 173633,
      explicit: true,
      external_ids: {
        isrc: "USUM72203764",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3Wx98ijEDnsxyMYePCuFNI",
      },
      href: "https://api.spotify.com/v1/tracks/3Wx98ijEDnsxyMYePCuFNI",
      id: "3Wx98ijEDnsxyMYePCuFNI",
      is_local: false,
      name: "Dreamin Of The Past (feat. Kanye West)",
      popularity: 65,
      preview_url:
        "https://p.scdn.co/mp3-preview/c4e0449680eb937483478804bf60dbb00ac7f458?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 3,
      type: "track",
      uri: "spotify:track:3Wx98ijEDnsxyMYePCuFNI",
    },
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3YYbAExunnHv5pW7GUZefk",
            },
            href: "https://api.spotify.com/v1/artists/3YYbAExunnHv5pW7GUZefk",
            id: "3YYbAExunnHv5pW7GUZefk",
            name: "DC The Don",
            type: "artist",
            uri: "spotify:artist:3YYbAExunnHv5pW7GUZefk",
          },
        ],
        available_markets: [],
        external_urls: {
          spotify: "https://open.spotify.com/album/5ZX7fpWcOQ4N6zDaQpjTtB",
        },
        href: "https://api.spotify.com/v1/albums/5ZX7fpWcOQ4N6zDaQpjTtB",
        id: "5ZX7fpWcOQ4N6zDaQpjTtB",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273c9918baa6be887e230425068",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02c9918baa6be887e230425068",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851c9918baa6be887e230425068",
            width: 64,
          },
        ],
        name: "DC Fridays",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 5,
        type: "album",
        uri: "spotify:album:5ZX7fpWcOQ4N6zDaQpjTtB",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3YYbAExunnHv5pW7GUZefk",
          },
          href: "https://api.spotify.com/v1/artists/3YYbAExunnHv5pW7GUZefk",
          id: "3YYbAExunnHv5pW7GUZefk",
          name: "DC The Don",
          type: "artist",
          uri: "spotify:artist:3YYbAExunnHv5pW7GUZefk",
        },
      ],
      available_markets: [],
      disc_number: 1,
      duration_ms: 228581,
      explicit: true,
      external_ids: {
        isrc: "USA2P1960719",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/7vQR7XKp7KnsQj264aaCDG",
      },
      href: "https://api.spotify.com/v1/tracks/7vQR7XKp7KnsQj264aaCDG",
      id: "7vQR7XKp7KnsQj264aaCDG",
      is_local: false,
      name: "TBH YuR CooL RaTe 8",
      popularity: 17,
      preview_url: null,
      track_number: 3,
      type: "track",
      uri: "spotify:track:7vQR7XKp7KnsQj264aaCDG",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3YYbAExunnHv5pW7GUZefk",
            },
            href: "https://api.spotify.com/v1/artists/3YYbAExunnHv5pW7GUZefk",
            id: "3YYbAExunnHv5pW7GUZefk",
            name: "DC The Don",
            type: "artist",
            uri: "spotify:artist:3YYbAExunnHv5pW7GUZefk",
          },
        ],
        available_markets: [],
        external_urls: {
          spotify: "https://open.spotify.com/album/6ckER45wIkPUkk6neIxSsN",
        },
        href: "https://api.spotify.com/v1/albums/6ckER45wIkPUkk6neIxSsN",
        id: "6ckER45wIkPUkk6neIxSsN",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2734889a9fc25a33dee72a75cd1",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e024889a9fc25a33dee72a75cd1",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048514889a9fc25a33dee72a75cd1",
            width: 64,
          },
        ],
        name: "Come As You Are",
        release_date: "2020-08-07",
        release_date_precision: "day",
        total_tracks: 14,
        type: "album",
        uri: "spotify:album:6ckER45wIkPUkk6neIxSsN",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3YYbAExunnHv5pW7GUZefk",
          },
          href: "https://api.spotify.com/v1/artists/3YYbAExunnHv5pW7GUZefk",
          id: "3YYbAExunnHv5pW7GUZefk",
          name: "DC The Don",
          type: "artist",
          uri: "spotify:artist:3YYbAExunnHv5pW7GUZefk",
        },
      ],
      available_markets: [],
      disc_number: 1,
      duration_ms: 185930,
      explicit: true,
      external_ids: {
        isrc: "USA2P2018659",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/2mlCOugxELgGvIn7MQramy",
      },
      href: "https://api.spotify.com/v1/tracks/2mlCOugxELgGvIn7MQramy",
      id: "2mlCOugxELgGvIn7MQramy",
      is_local: false,
      name: "Jesus Can't Save You",
      popularity: 14,
      preview_url: null,
      track_number: 6,
      type: "track",
      uri: "spotify:track:2mlCOugxELgGvIn7MQramy",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/13ZEDW6vyBF12HYcZRr4EV",
            },
            href: "https://api.spotify.com/v1/artists/13ZEDW6vyBF12HYcZRr4EV",
            id: "13ZEDW6vyBF12HYcZRr4EV",
            name: "Tyler Childers",
            type: "artist",
            uri: "spotify:artist:13ZEDW6vyBF12HYcZRr4EV",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/35LcGAeeMwVeIJrDpB3Gkz",
        },
        href: "https://api.spotify.com/v1/albums/35LcGAeeMwVeIJrDpB3Gkz",
        id: "35LcGAeeMwVeIJrDpB3Gkz",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2735a38bd36056b909ed607689d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e025a38bd36056b909ed607689d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048515a38bd36056b909ed607689d",
            width: 64,
          },
        ],
        name: "Purgatory",
        release_date: "2017-08-04",
        release_date_precision: "day",
        total_tracks: 10,
        type: "album",
        uri: "spotify:album:35LcGAeeMwVeIJrDpB3Gkz",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/13ZEDW6vyBF12HYcZRr4EV",
          },
          href: "https://api.spotify.com/v1/artists/13ZEDW6vyBF12HYcZRr4EV",
          id: "13ZEDW6vyBF12HYcZRr4EV",
          name: "Tyler Childers",
          type: "artist",
          uri: "spotify:artist:13ZEDW6vyBF12HYcZRr4EV",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 224946,
      explicit: true,
      external_ids: {
        isrc: "QZ84K1700002",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/2tgQaL85WoRfgEa4hFQgrE",
      },
      href: "https://api.spotify.com/v1/tracks/2tgQaL85WoRfgEa4hFQgrE",
      id: "2tgQaL85WoRfgEa4hFQgrE",
      is_local: false,
      name: "Feathered Indians",
      popularity: 81,
      preview_url:
        "https://p.scdn.co/mp3-preview/c94b286f003f6aa9e3141b4496db809aeaa70ead?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 2,
      type: "track",
      uri: "spotify:track:2tgQaL85WoRfgEa4hFQgrE",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/13ZEDW6vyBF12HYcZRr4EV",
            },
            href: "https://api.spotify.com/v1/artists/13ZEDW6vyBF12HYcZRr4EV",
            id: "13ZEDW6vyBF12HYcZRr4EV",
            name: "Tyler Childers",
            type: "artist",
            uri: "spotify:artist:13ZEDW6vyBF12HYcZRr4EV",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/35LcGAeeMwVeIJrDpB3Gkz",
        },
        href: "https://api.spotify.com/v1/albums/35LcGAeeMwVeIJrDpB3Gkz",
        id: "35LcGAeeMwVeIJrDpB3Gkz",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2735a38bd36056b909ed607689d",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e025a38bd36056b909ed607689d",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048515a38bd36056b909ed607689d",
            width: 64,
          },
        ],
        name: "Purgatory",
        release_date: "2017-08-04",
        release_date_precision: "day",
        total_tracks: 10,
        type: "album",
        uri: "spotify:album:35LcGAeeMwVeIJrDpB3Gkz",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/13ZEDW6vyBF12HYcZRr4EV",
          },
          href: "https://api.spotify.com/v1/artists/13ZEDW6vyBF12HYcZRr4EV",
          id: "13ZEDW6vyBF12HYcZRr4EV",
          name: "Tyler Childers",
          type: "artist",
          uri: "spotify:artist:13ZEDW6vyBF12HYcZRr4EV",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 183533,
      explicit: false,
      external_ids: {
        isrc: "QZ84K1700010",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3t5OV1asJHmOlf23T08CLv",
      },
      href: "https://api.spotify.com/v1/tracks/3t5OV1asJHmOlf23T08CLv",
      id: "3t5OV1asJHmOlf23T08CLv",
      is_local: false,
      name: "Lady May",
      popularity: 79,
      preview_url:
        "https://p.scdn.co/mp3-preview/582f1a2e2646fc930fcc90a63a74ae3ca52f41f2?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 10,
      type: "track",
      uri: "spotify:track:3t5OV1asJHmOlf23T08CLv",
    },
  ],
  total: 50,
  limit: 5,
  offset: 0,
  href: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=0&time_range=long_term",
  next: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=5&time_range=long_term",
  previous: null,
};
const mediumTerm = {
  items: [
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5ZZsFnpO7frU8h5xH1wtjT",
            },
            href: "https://api.spotify.com/v1/artists/5ZZsFnpO7frU8h5xH1wtjT",
            id: "5ZZsFnpO7frU8h5xH1wtjT",
            name: "Saint Levant",
            type: "artist",
            uri: "spotify:artist:5ZZsFnpO7frU8h5xH1wtjT",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SK",
          "SV",
          "TN",
          "TR",
          "UY",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5bah1OVDvcvn92BMkgOO6o",
        },
        href: "https://api.spotify.com/v1/albums/5bah1OVDvcvn92BMkgOO6o",
        id: "5bah1OVDvcvn92BMkgOO6o",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2737ebb8e22ad63a712a3b7a025",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e027ebb8e22ad63a712a3b7a025",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048517ebb8e22ad63a712a3b7a025",
            width: 64,
          },
        ],
        name: "From Gaza, With Love",
        release_date: "2023-03-06",
        release_date_precision: "day",
        total_tracks: 7,
        type: "album",
        uri: "spotify:album:5bah1OVDvcvn92BMkgOO6o",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5ZZsFnpO7frU8h5xH1wtjT",
          },
          href: "https://api.spotify.com/v1/artists/5ZZsFnpO7frU8h5xH1wtjT",
          id: "5ZZsFnpO7frU8h5xH1wtjT",
          name: "Saint Levant",
          type: "artist",
          uri: "spotify:artist:5ZZsFnpO7frU8h5xH1wtjT",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SK",
        "SV",
        "TN",
        "TR",
        "UY",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 119747,
      explicit: false,
      external_ids: {
        isrc: "TLSAI2300002",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/49AG4MU3Ij6a8NWEVLMuRu",
      },
      href: "https://api.spotify.com/v1/tracks/49AG4MU3Ij6a8NWEVLMuRu",
      id: "49AG4MU3Ij6a8NWEVLMuRu",
      is_local: false,
      name: "From Gaza, With Love",
      popularity: 60,
      preview_url:
        "https://p.scdn.co/mp3-preview/aecf5533379801d817900bbf50846f0ebc53bee2?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 2,
      type: "track",
      uri: "spotify:track:49AG4MU3Ij6a8NWEVLMuRu",
    },
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1fZpYWNWdL5Z3wrDtISFUH",
            },
            href: "https://api.spotify.com/v1/artists/1fZpYWNWdL5Z3wrDtISFUH",
            id: "1fZpYWNWdL5Z3wrDtISFUH",
            name: "Shakey Graves",
            type: "artist",
            uri: "spotify:artist:1fZpYWNWdL5Z3wrDtISFUH",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6gtu2oXhmDQN8TAsWimZbj",
        },
        href: "https://api.spotify.com/v1/albums/6gtu2oXhmDQN8TAsWimZbj",
        id: "6gtu2oXhmDQN8TAsWimZbj",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273d9e9693926785359f903acb5",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02d9e9693926785359f903acb5",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851d9e9693926785359f903acb5",
            width: 64,
          },
        ],
        name: "Tomorrow",
        release_date: "2016-09-02",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:6gtu2oXhmDQN8TAsWimZbj",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1fZpYWNWdL5Z3wrDtISFUH",
          },
          href: "https://api.spotify.com/v1/artists/1fZpYWNWdL5Z3wrDtISFUH",
          id: "1fZpYWNWdL5Z3wrDtISFUH",
          name: "Shakey Graves",
          type: "artist",
          uri: "spotify:artist:1fZpYWNWdL5Z3wrDtISFUH",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 240586,
      explicit: false,
      external_ids: {
        isrc: "USDMG1677702",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/47KDDZgFiX1w6RFOuLXsSn",
      },
      href: "https://api.spotify.com/v1/tracks/47KDDZgFiX1w6RFOuLXsSn",
      id: "47KDDZgFiX1w6RFOuLXsSn",
      is_local: false,
      name: "Tomorrow",
      popularity: 69,
      preview_url:
        "https://p.scdn.co/mp3-preview/09725d2a751320dc8333c0252402585ba4e9857c?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:47KDDZgFiX1w6RFOuLXsSn",
    },
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/40ZNYROS4zLfyyBSs2PGe2",
            },
            href: "https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2",
            id: "40ZNYROS4zLfyyBSs2PGe2",
            name: "Zach Bryan",
            type: "artist",
            uri: "spotify:artist:40ZNYROS4zLfyyBSs2PGe2",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4NZvixzsSefsNiIqXn0NDe",
            },
            href: "https://api.spotify.com/v1/artists/4NZvixzsSefsNiIqXn0NDe",
            id: "4NZvixzsSefsNiIqXn0NDe",
            name: "Maggie Rogers",
            type: "artist",
            uri: "spotify:artist:4NZvixzsSefsNiIqXn0NDe",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/2Wpz5Xzsbr7hJg5Wb13p4m",
        },
        href: "https://api.spotify.com/v1/albums/2Wpz5Xzsbr7hJg5Wb13p4m",
        id: "2Wpz5Xzsbr7hJg5Wb13p4m",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273a0a916db0206cc4d773f9013",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02a0a916db0206cc4d773f9013",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851a0a916db0206cc4d773f9013",
            width: 64,
          },
        ],
        name: "Dawns (feat. Maggie Rogers)",
        release_date: "2023-01-27",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:2Wpz5Xzsbr7hJg5Wb13p4m",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/40ZNYROS4zLfyyBSs2PGe2",
          },
          href: "https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2",
          id: "40ZNYROS4zLfyyBSs2PGe2",
          name: "Zach Bryan",
          type: "artist",
          uri: "spotify:artist:40ZNYROS4zLfyyBSs2PGe2",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4NZvixzsSefsNiIqXn0NDe",
          },
          href: "https://api.spotify.com/v1/artists/4NZvixzsSefsNiIqXn0NDe",
          id: "4NZvixzsSefsNiIqXn0NDe",
          name: "Maggie Rogers",
          type: "artist",
          uri: "spotify:artist:4NZvixzsSefsNiIqXn0NDe",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 290892,
      explicit: true,
      external_ids: {
        isrc: "USWB12300176",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/42TtHTxWk782ZBiqyOi2d1",
      },
      href: "https://api.spotify.com/v1/tracks/42TtHTxWk782ZBiqyOi2d1",
      id: "42TtHTxWk782ZBiqyOi2d1",
      is_local: false,
      name: "Dawns (feat. Maggie Rogers)",
      popularity: 80,
      preview_url:
        "https://p.scdn.co/mp3-preview/483cecffd0bb8f592b71fa20e90c2a9177b0de70?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 1,
      type: "track",
      uri: "spotify:track:42TtHTxWk782ZBiqyOi2d1",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/40ZNYROS4zLfyyBSs2PGe2",
            },
            href: "https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2",
            id: "40ZNYROS4zLfyyBSs2PGe2",
            name: "Zach Bryan",
            type: "artist",
            uri: "spotify:artist:40ZNYROS4zLfyyBSs2PGe2",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/7IouDrXPdAZwT1NzVV3vef",
        },
        href: "https://api.spotify.com/v1/albums/7IouDrXPdAZwT1NzVV3vef",
        id: "7IouDrXPdAZwT1NzVV3vef",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273ba30859a1ca79c5a372d177a",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02ba30859a1ca79c5a372d177a",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851ba30859a1ca79c5a372d177a",
            width: 64,
          },
        ],
        name: "American Heartbreak",
        release_date: "2022-05-20",
        release_date_precision: "day",
        total_tracks: 34,
        type: "album",
        uri: "spotify:album:7IouDrXPdAZwT1NzVV3vef",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/40ZNYROS4zLfyyBSs2PGe2",
          },
          href: "https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2",
          id: "40ZNYROS4zLfyyBSs2PGe2",
          name: "Zach Bryan",
          type: "artist",
          uri: "spotify:artist:40ZNYROS4zLfyyBSs2PGe2",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 188882,
      explicit: false,
      external_ids: {
        isrc: "USWB12201484",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1TsiwVwHhLgVK8sxBchINM",
      },
      href: "https://api.spotify.com/v1/tracks/1TsiwVwHhLgVK8sxBchINM",
      id: "1TsiwVwHhLgVK8sxBchINM",
      is_local: false,
      name: "Tishomingo",
      popularity: 71,
      preview_url:
        "https://p.scdn.co/mp3-preview/012e94cb9ecc68c27872f1daa1fcfc6bd980bb7c?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 10,
      type: "track",
      uri: "spotify:track:1TsiwVwHhLgVK8sxBchINM",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5XKFrudbV4IiuE5WuTPRmT",
            },
            href: "https://api.spotify.com/v1/artists/5XKFrudbV4IiuE5WuTPRmT",
            id: "5XKFrudbV4IiuE5WuTPRmT",
            name: "Stephen Sanchez",
            type: "artist",
            uri: "spotify:artist:5XKFrudbV4IiuE5WuTPRmT",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6BUPtXbb2tspYnkVdg5Ef7",
        },
        href: "https://api.spotify.com/v1/albums/6BUPtXbb2tspYnkVdg5Ef7",
        id: "6BUPtXbb2tspYnkVdg5Ef7",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2739522042f86d0bb0d4e9e3783",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e029522042f86d0bb0d4e9e3783",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048519522042f86d0bb0d4e9e3783",
            width: 64,
          },
        ],
        name: "Easy On My Eyes",
        release_date: "2022-08-19",
        release_date_precision: "day",
        total_tracks: 7,
        type: "album",
        uri: "spotify:album:6BUPtXbb2tspYnkVdg5Ef7",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/5XKFrudbV4IiuE5WuTPRmT",
          },
          href: "https://api.spotify.com/v1/artists/5XKFrudbV4IiuE5WuTPRmT",
          id: "5XKFrudbV4IiuE5WuTPRmT",
          name: "Stephen Sanchez",
          type: "artist",
          uri: "spotify:artist:5XKFrudbV4IiuE5WuTPRmT",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 180146,
      explicit: false,
      external_ids: {
        isrc: "USUG12205973",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/5nsFJfYtAFZmL9PbtYKYcA",
      },
      href: "https://api.spotify.com/v1/tracks/5nsFJfYtAFZmL9PbtYKYcA",
      id: "5nsFJfYtAFZmL9PbtYKYcA",
      is_local: false,
      name: "See The Light",
      popularity: 67,
      preview_url:
        "https://p.scdn.co/mp3-preview/e7fc78170429a5adb009033137518fea2ebea66e?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 2,
      type: "track",
      uri: "spotify:track:5nsFJfYtAFZmL9PbtYKYcA",
    },
  ],
  total: 50,
  limit: 5,
  offset: 0,
  href: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=0",
  next: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=5",
  previous: null,
};
const shortTerm = {
  items: [
    {
      album: {
        album_type: "SINGLE",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6cSxzHrQgGc4I4Ck5Gewej",
            },
            href: "https://api.spotify.com/v1/artists/6cSxzHrQgGc4I4Ck5Gewej",
            id: "6cSxzHrQgGc4I4Ck5Gewej",
            name: "Sons Of The East",
            type: "artist",
            uri: "spotify:artist:6cSxzHrQgGc4I4Ck5Gewej",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1vZr8u4hOxmP6xvBgZUPMd",
        },
        href: "https://api.spotify.com/v1/albums/1vZr8u4hOxmP6xvBgZUPMd",
        id: "1vZr8u4hOxmP6xvBgZUPMd",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b4d3b2740b535c9b56210df1",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b4d3b2740b535c9b56210df1",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b4d3b2740b535c9b56210df1",
            width: 64,
          },
        ],
        name: "Sons Of The East",
        release_date: "2013-08-02",
        release_date_precision: "day",
        total_tracks: 5,
        type: "album",
        uri: "spotify:album:1vZr8u4hOxmP6xvBgZUPMd",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6cSxzHrQgGc4I4Ck5Gewej",
          },
          href: "https://api.spotify.com/v1/artists/6cSxzHrQgGc4I4Ck5Gewej",
          id: "6cSxzHrQgGc4I4Ck5Gewej",
          name: "Sons Of The East",
          type: "artist",
          uri: "spotify:artist:6cSxzHrQgGc4I4Ck5Gewej",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 222186,
      explicit: false,
      external_ids: {
        isrc: "AUGNB1300005",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/46BuJdwxV43a6qLrICP27l",
      },
      href: "https://api.spotify.com/v1/tracks/46BuJdwxV43a6qLrICP27l",
      id: "46BuJdwxV43a6qLrICP27l",
      is_local: false,
      name: "California",
      popularity: 61,
      preview_url:
        "https://p.scdn.co/mp3-preview/8113cb556155a6295bc777f99e0c484fc05b2a04?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 5,
      type: "track",
      uri: "spotify:track:46BuJdwxV43a6qLrICP27l",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2jku7tDXc6XoB6MO2hFuqg",
            },
            href: "https://api.spotify.com/v1/artists/2jku7tDXc6XoB6MO2hFuqg",
            id: "2jku7tDXc6XoB6MO2hFuqg",
            name: "Tory Lanez",
            type: "artist",
            uri: "spotify:artist:2jku7tDXc6XoB6MO2hFuqg",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6vVhekA9LRg0MWIQaxI37f",
        },
        href: "https://api.spotify.com/v1/albums/6vVhekA9LRg0MWIQaxI37f",
        id: "6vVhekA9LRg0MWIQaxI37f",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b2733f5d63f12fa8e44a86936e07",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e023f5d63f12fa8e44a86936e07",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d000048513f5d63f12fa8e44a86936e07",
            width: 64,
          },
        ],
        name: "Chixtape 5",
        release_date: "2019-11-15",
        release_date_precision: "day",
        total_tracks: 18,
        type: "album",
        uri: "spotify:album:6vVhekA9LRg0MWIQaxI37f",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2jku7tDXc6XoB6MO2hFuqg",
          },
          href: "https://api.spotify.com/v1/artists/2jku7tDXc6XoB6MO2hFuqg",
          id: "2jku7tDXc6XoB6MO2hFuqg",
          name: "Tory Lanez",
          type: "artist",
          uri: "spotify:artist:2jku7tDXc6XoB6MO2hFuqg",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/1Xfmvd48oOhEWkscWyEbh9",
          },
          href: "https://api.spotify.com/v1/artists/1Xfmvd48oOhEWkscWyEbh9",
          id: "1Xfmvd48oOhEWkscWyEbh9",
          name: "Lloyd",
          type: "artist",
          uri: "spotify:artist:1Xfmvd48oOhEWkscWyEbh9",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/55Aa2cqylxrFIXC767Z865",
          },
          href: "https://api.spotify.com/v1/artists/55Aa2cqylxrFIXC767Z865",
          id: "55Aa2cqylxrFIXC767Z865",
          name: "Lil Wayne",
          type: "artist",
          uri: "spotify:artist:55Aa2cqylxrFIXC767Z865",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 333546,
      explicit: true,
      external_ids: {
        isrc: "USUM71922088",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/1kWAhf2TJPkpiSgTnp8Ure",
      },
      href: "https://api.spotify.com/v1/tracks/1kWAhf2TJPkpiSgTnp8Ure",
      id: "1kWAhf2TJPkpiSgTnp8Ure",
      is_local: false,
      name: "Thoughts (feat. Lloyd & Lil Wayne)",
      popularity: 53,
      preview_url:
        "https://p.scdn.co/mp3-preview/f3494b2ad177aea9c8c04af4c5de4417430bcd89?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 15,
      type: "track",
      uri: "spotify:track:1kWAhf2TJPkpiSgTnp8Ure",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2ErsJAz6qJ5cqjoVAvfvaC",
            },
            href: "https://api.spotify.com/v1/artists/2ErsJAz6qJ5cqjoVAvfvaC",
            id: "2ErsJAz6qJ5cqjoVAvfvaC",
            name: "Charles Wesley Godwin",
            type: "artist",
            uri: "spotify:artist:2ErsJAz6qJ5cqjoVAvfvaC",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0FazkbocfVJ5apOEfeCUsE",
        },
        href: "https://api.spotify.com/v1/albums/0FazkbocfVJ5apOEfeCUsE",
        id: "0FazkbocfVJ5apOEfeCUsE",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b1968034cd5d3d3ca2411da7",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b1968034cd5d3d3ca2411da7",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b1968034cd5d3d3ca2411da7",
            width: 64,
          },
        ],
        name: "Seneca",
        release_date: "2019-02-15",
        release_date_precision: "day",
        total_tracks: 12,
        type: "album",
        uri: "spotify:album:0FazkbocfVJ5apOEfeCUsE",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/2ErsJAz6qJ5cqjoVAvfvaC",
          },
          href: "https://api.spotify.com/v1/artists/2ErsJAz6qJ5cqjoVAvfvaC",
          id: "2ErsJAz6qJ5cqjoVAvfvaC",
          name: "Charles Wesley Godwin",
          type: "artist",
          uri: "spotify:artist:2ErsJAz6qJ5cqjoVAvfvaC",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 240956,
      explicit: false,
      external_ids: {
        isrc: "QM9AA1854863",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/7BAb0MMi9vrX68buZqzyLa",
      },
      href: "https://api.spotify.com/v1/tracks/7BAb0MMi9vrX68buZqzyLa",
      id: "7BAb0MMi9vrX68buZqzyLa",
      is_local: false,
      name: "Hardwood Floors",
      popularity: 57,
      preview_url:
        "https://p.scdn.co/mp3-preview/3ebc428ecef9f1f596d423cf24ddd3fbce89ea69?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 3,
      type: "track",
      uri: "spotify:track:7BAb0MMi9vrX68buZqzyLa",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
            },
            href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
            id: "4LLpKhyESsyAXpc4laK94U",
            name: "Mac Miller",
            type: "artist",
            uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/5LNX3esjvdBJ6hN4XDvCJn",
        },
        href: "https://api.spotify.com/v1/albums/5LNX3esjvdBJ6hN4XDvCJn",
        id: "5LNX3esjvdBJ6hN4XDvCJn",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273c8a77225ad852699c908ac4b",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02c8a77225ad852699c908ac4b",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851c8a77225ad852699c908ac4b",
            width: 64,
          },
        ],
        name: "I Love Life, Thank You",
        release_date: "2022-07-22",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:5LNX3esjvdBJ6hN4XDvCJn",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4LLpKhyESsyAXpc4laK94U",
          },
          href: "https://api.spotify.com/v1/artists/4LLpKhyESsyAXpc4laK94U",
          id: "4LLpKhyESsyAXpc4laK94U",
          name: "Mac Miller",
          type: "artist",
          uri: "spotify:artist:4LLpKhyESsyAXpc4laK94U",
        },
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/4W48hZAnAHVOC2c8WH8pcq",
          },
          href: "https://api.spotify.com/v1/artists/4W48hZAnAHVOC2c8WH8pcq",
          id: "4W48hZAnAHVOC2c8WH8pcq",
          name: "The Temper Trap",
          type: "artist",
          uri: "spotify:artist:4W48hZAnAHVOC2c8WH8pcq",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 162875,
      explicit: true,
      external_ids: {
        isrc: "USA2P2212493",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/2z9iuAxKv4TTeCrPAxxKg9",
      },
      href: "https://api.spotify.com/v1/tracks/2z9iuAxKv4TTeCrPAxxKg9",
      id: "2z9iuAxKv4TTeCrPAxxKg9",
      is_local: false,
      name: "Love Lost",
      popularity: 80,
      preview_url:
        "https://p.scdn.co/mp3-preview/00be55b4568a2fe3985459db905d3e9ca2d845fd?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 5,
      type: "track",
      uri: "spotify:track:2z9iuAxKv4TTeCrPAxxKg9",
    },
    {
      album: {
        album_type: "ALBUM",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/69tiO1fG8VWduDl3ji2qhI",
            },
            href: "https://api.spotify.com/v1/artists/69tiO1fG8VWduDl3ji2qhI",
            id: "69tiO1fG8VWduDl3ji2qhI",
            name: "Mt. Joy",
            type: "artist",
            uri: "spotify:artist:69tiO1fG8VWduDl3ji2qhI",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0JEbkW1a2Ws7P8vMflSPc9",
        },
        href: "https://api.spotify.com/v1/albums/0JEbkW1a2Ws7P8vMflSPc9",
        id: "0JEbkW1a2Ws7P8vMflSPc9",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273b2cb94f2febe2df19963b6e4",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02b2cb94f2febe2df19963b6e4",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851b2cb94f2febe2df19963b6e4",
            width: 64,
          },
        ],
        name: "Rearrange Us",
        release_date: "2020-06-05",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:0JEbkW1a2Ws7P8vMflSPc9",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/69tiO1fG8VWduDl3ji2qhI",
          },
          href: "https://api.spotify.com/v1/artists/69tiO1fG8VWduDl3ji2qhI",
          id: "69tiO1fG8VWduDl3ji2qhI",
          name: "Mt. Joy",
          type: "artist",
          uri: "spotify:artist:69tiO1fG8VWduDl3ji2qhI",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      disc_number: 1,
      duration_ms: 193186,
      explicit: false,
      external_ids: {
        isrc: "USDMG2000613",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/3wcluZHyfuTzIXHfwXVAIE",
      },
      href: "https://api.spotify.com/v1/tracks/3wcluZHyfuTzIXHfwXVAIE",
      id: "3wcluZHyfuTzIXHfwXVAIE",
      is_local: false,
      name: "Strangers",
      popularity: 70,
      preview_url:
        "https://p.scdn.co/mp3-preview/4e6e4fbccd10e7c2447b8ad7479e9b76c231cfbe?cid=0b297fa8a249464ba34f5861d4140e58",
      track_number: 13,
      type: "track",
      uri: "spotify:track:3wcluZHyfuTzIXHfwXVAIE",
    },
  ],
  total: 50,
  limit: 5,
  offset: 0,
  href: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=0&time_range=short_term",
  next: "https://api.spotify.com/v1/me/top/tracks?limit=5&offset=5&time_range=short_term",
  previous: null,
};

function MyTopTracks() {
  const [selectedTerm, setSelectedTerm] = useState("shortTerm");

  const handleChange = (event) => {
    setSelectedTerm(event.target.value);
  };

  const termData = {
    longTerm: longTerm,
    mediumTerm: mediumTerm,
    shortTerm: shortTerm,
  };

  const selectedData = termData[selectedTerm];

  return (
    <>
      <CssBaseline />
      <div>
        <Container maxWidth="lg">
          <Grid container spacing={4} justify="left">
            <Grid item xs={12}>
              <Select value={selectedTerm} onChange={handleChange}>
                <MenuItem value="longTerm">Long Term</MenuItem>
                <MenuItem value="mediumTerm">Medium Term</MenuItem>
                <MenuItem value="shortTerm">Short Term</MenuItem>
              </Select>
            </Grid>
            {selectedData.items.map((track) => (
              <Grid item xs={12} sm={6} md={3} lg={3} key={track.id}>
                <Card style={{ height: "100%" }}>
                  <CardMedia
                    style={{ paddingTop: "56.35%" }}
                    image={track.album.images[0].url}
                    title={track.name}
                  />
                  <CardContent style={{ flexGrow: 1 }}>
                    <Typography variant="h6" component="div" gutterBottom>
                      {track.name}
                    </Typography>
                    <Typography variant="body2" color="textSecondary">
                      Artist: {track.artists[0].name}
                    </Typography>
                    <Typography variant="body2" color="textSecondary">
                      Popularity: {track.popularity}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </div>
    </>
  );
}

export default MyTopTracks;
